Repository fairmingos/frc-2020, pull requests merged in 2020-02, with the labels that each got.

#9 added functionality for reversing drive direction with joystick 'thro…
  src/main/kotlin/frc/robot/OI.kt
  src/main/kotlin/frc/robot/commands/DriveCommand.kt
  src/test/kotlin/frc/robot/commands/DriveCommandSpec.kt
Labels: enhancement

#11 refactored for four motor controllers (instead of two)
  src/main/kotlin/frc/robot/Constants.kt
  src/main/kotlin/frc/robot/RobotContainer.kt
Labels: bug, enhancement

#12 reversed throttle output in oi, gets wrong direction
  src/main/kotlin/frc/robot/OI.kt
Labels: bug

#15 added ReleaseArmCommand.kt, ArmSubsystem.kt, and tests; implemented i…
  src/main/kotlin/frc/robot/Constants.kt
  src/main/kotlin/frc/robot/RobotContainer.kt
  src/main/kotlin/frc/robot/commands/ReleaseArmCommand.kt
  src/main/kotlin/frc/robot/subsystems/ArmSubsystem.kt
  src/test/kotlin/frc/robot/commands/AutonomousDriveSpec.kt
  src/test/kotlin/frc/robot/commands/ReleaseArmSpec.kt
  src/test/kotlin/frc/robot/subsystems/ArmSubsystemSpec.kt
  src/test/kotlin/frc/robot/subsystems/DriveSubsystemSpec.kt
Labels: enhancement
